# -*- coding: utf-8 -*-
"""Prometheus_2.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aM-EYmZGhJj6xqGlfOaKEDxljbUEDEtb

#STOCKS LIST DEFINE
"""

NIFTY100 = [
    "ABB.NS",
    "ACC.NS",
    "ADANIENT.NS",
    "ADANIGREEN.NS",
    "ADANIENSOL.NS",
    "ADANIPORTS.NS",
    "ADANIPOWER.NS",
    "ATGL.NS",
    "AMBUJACEM.NS",
    "APOLLOHOSP.NS",
    "ASIANPAINT.NS",
    "DMART.NS",
    "AXISBANK.NS",
    "BAJAJ-AUTO.NS",
    "BAJFINANCE.NS",
    "BAJAJFINSV.NS",
    "BAJAJHLDNG.NS",
    "BANKBARODA.NS",
    "BEL.NS",
    "BERGEPAINT.NS",
    "BHARATFORG.NS",
    "BHARTIARTL.NS",
    "BHEL.NS",
    "BPCL.NS",
    "BIOCON.NS",
    "BOSCHLTD.NS",
    "BRITANNIA.NS",
    "CANBK.NS",
    "CGPOWER.NS",
    "CHOLAFIN.NS",
    "CIPLA.NS",
    "COALINDIA.NS",
    "COLPAL.NS",
    "CONCOR.NS",
    "CUMMINSIND.NS",
    "DABUR.NS",
    "DIVISLAB.NS",
    "DLF.NS",
    "DRREDDY.NS",
    "EICHERMOT.NS",
    "GAIL.NS",
    "GODREJCP.NS",
    "GRASIM.NS",
    "HAL.NS",
    "HAVELLS.NS",
    "HCLTECH.NS",
    "HDFCBANK.NS",
    "HDFCLIFE.NS",
    "HEROMOTOCO.NS",
    "HINDALCO.NS",
    "HINDUNILVR.NS",
    "HINDZINC.NS",
    "ICICIBANK.NS",
    "ICICIGI.NS",
    "ICICIPRULI.NS",
    "IOC.NS",
    "IRCTC.NS",
    "IRFC.NS",
    "ITC.NS",
    "INDIGO.NS",
    "INDUSINDBK.NS",
    "INFOEDGE.NS",
    "INFY.NS",
    "JINDALSTEL.NS",
    "JIOFIN.NS",
    "JSWENERGY.NS",
    "JSWSTEEL.NS",
    "KOTAKBANK.NS",
    "LT.NS",
    "LICI.NS",
    "LTIM.NS",
    "M&M.NS",
    "MARICO.NS",
    "MARUTI.NS",
    "MAXHEALTH.NS",
    "MAZDOCK.NS",
    "MOTHERSON.NS",
    "NESTLEIND.NS",
    "NHPC.NS",
    "NTPC.NS",
    "ONGC.NS",
    "PFC.NS",
    "PIDILITIND.NS",
    "PNB.NS",
    "POWERGRID.NS",
    "PGHH.NS",
    "RECLTD.NS",
    "RELIANCE.NS",
    "SBICARD.NS",
    "SBILIFE.NS",
    "SBIN.NS",
    "SHREECEM.NS",
    "SHRIRAMFIN.NS",
    "SIEMENS.NS",
    "SRF.NS",
    "SUNPHARMA.NS",
    "TCS.NS",
    "TATACONSUM.NS",
    "TATAMOTORS.NS",
    "TATAPOWER.NS",
    "TATASTEEL.NS",
    "TECHM.NS",
    "TITAN.NS",
    "TORNTPHARM.NS",
    "TRENT.NS",
    "TVSMOTOR.NS",
    "ULTRACEMCO.NS",
    "UNIONBANK.NS",
    "UNITDSPR.NS",
    "VBL.NS",
    "VEDL.NS",
    "WIPRO.NS",
    "ZOMATO.NS",
    "ZYDUSLIFE.NS"
]

LARGE_CAP_STOCKS = [
    "ADANIENT.NS",
    "ADANIPORTS.NS",
    "APOLLOHOSP.NS",
    "ASIANPAINT.NS",
    "AXISBANK.NS",
    "BAJAJ-AUTO.NS",
    "BAJFINANCE.NS",
    "BAJAJFINSV.NS",
    "BPCL.NS",
    "BHARTIARTL.NS",
    "BRITANNIA.NS",
    "CIPLA.NS",
    "COALINDIA.NS",
    "DIVISLAB.NS",
    "DRREDDY.NS",
    "EICHERMOT.NS",
    "GRASIM.NS",
    "HCLTECH.NS",
    "HDFCBANK.NS",
    "HDFCLIFE.NS",
    "HEROMOTOCO.NS",
    "HINDALCO.NS",
    "HINDUNILVR.NS",
    "ICICIBANK.NS",
    "ITC.NS",
    "INDUSINDBK.NS",
    "INFY.NS",
    "JSWSTEEL.NS",
    "KOTAKBANK.NS",
    "LTIM.NS",
    "LT.NS",
    "M&M.NS",
    "MARUTI.NS",
    "NESTLEIND.NS",
    "NTPC.NS",
    "ONGC.NS",
    "POWERGRID.NS",
    "RELIANCE.NS",
    "SBILIFE.NS",
    "SBIN.NS",
    "SUNPHARMA.NS",
    "TCS.NS",
    "TATACONSUM.NS",
    "TATAMOTORS.NS",
    "TATASTEEL.NS",
    "TECHM.NS",
    "TITAN.NS",
    "ULTRACEMCO.NS",
    "UPL.NS",
    "WIPRO.NS"
]

MID_CAP_STOCKS = [
    "ACC.NS",
    "ABFRL.NS",
    "AJANTPHARM.NS",
    "ALKEM.NS",
    "APLAPOLLO.NS",
    "APOLLOTYRE.NS",
    "ASHOKLEY.NS",
    "ASTRAL.NS",
    "AUBANK.NS",
    "AUROPHARMA.NS",
    "AWL.NS",
    "BALKRISIND.NS",
    "BANDHANBNK.NS",
    "BANKINDIA.NS",
    "BHEL.NS",
    "BERGEPAINT.NS",
    "BHARATFORG.NS",
    "BOSCHLTD.NS",
    "CANBK.NS",
    "CGPOWER.NS",
    "CHOLAFIN.NS",
    "COLPAL.NS",
    "CONCOR.NS",
    "COROMANDEL.NS",
    "CRISIL.NS",
    "CUMMINSIND.NS",
    "DALBHARAT.NS",
    "DEEPAKNTR.NS",
    "DELHIVERY.NS",
    "DIXON.NS",
    "EMAMI.NS",
    "ENDURANCE.NS",
    "ESCORTS.NS",
    "EXIDEIND.NS",
    "FACT.NS",
    "FEDERALBNK.NS",
    "FORTIS.NS",
    "GLAND.NS",
    "GMRINFRA.NS",
    "GODREJIND.NS",
    "GODREJPROP.NS",
    "GRINDWELL.NS",
    "GUJGASLTD.NS",
    "HDFCAMC.NS",
    "HPCL.NS",
    "HINDZINC.NS",
    "HONAUT.NS",
    "HUDCO.NS",
    "IDBI.NS",
    "IDEA.NS",
    "IDFCFIRSTB.NS",
    "IGL.NS",
    "INDHOTEL.NS",
    "INDIANB.NS",
    "INDUSTOWER.NS",
    "IOB.NS",
    "IPCALAB.NS",
    "IRB.NS",
    "IREDA.NS",
    "JKCEMENT.NS",
    "JINDALSTEL.NS",
    "JSWINFRA.NS",
    "JUBILANT.NS",
    "KALYANKJIL.NS",
    "KEI.NS",
    "KPITTECH.NS",
    "KPRMILL.NS",
    "LICHSGFIN.NS",
    "LINDEINDIA.NS",
    "LLOYDSME.NS",
    "LTF.NS",
    "LTTS.NS",
    "LUPIN.NS",
    "M&MFIN.NS",
    "MAHABANK.NS",
    "MANKIND.NS",
    "MARICO.NS",
    "MAXHEALTH.NS",
    "MAZDOCK.NS",
    "MEDANTA.NS",
    "METROBRAND.NS",
    "MFSL.NS",
    "MPHASIS.NS",
    "MRF.NS",
    "MRPL.NS",
    "MSUMI.NS",
    "MUTHOOTFIN.NS",
    "NAM-INDIA.NS",
    "NIACL.NS",
    "NLCINDIA.NS",
    "NMDC.NS",
    "NYKAA.NS",
    "OBEROIRLTY.NS",
    "OFSS.NS",
    "OIL.NS",
    "PAGEIND.NS",
    "PATANJALI.NS",
    "PAYTM.NS",
    "PERSISTENT.NS",
    "PETRONET.NS",
    "PGHH.NS",
    "PHOENIXLTD.NS",
    "PIIND.NS",
    "PBFINTECH.NS",
    "POLYCAB.NS",
    "POONAWALLA.NS",
    "POWERINDIA.NS",
    "PRESTIGE.NS",
    "RVNL.NS",
    "SAIL.NS",
    "SBICARD.NS",
    "SCHAEFFLER.NS",
    "SJVN.NS",
    "SKFINDIA.NS",
    "SOLARINDS.NS",
    "SONACOMS.NS",
    "SRF.NS",
    "STARHEALTH.NS",
    "SUNDARMFIN.NS",
    "SUNDRMFAST.NS",
    "SUNTV.NS",
    "SUPREMEIND.NS",
    "SUZLON.NS",
    "SYNGENE.NS",
    "TATACHEM.NS",
    "TATACOMM.NS",
    "TATAELXSI.NS",
    "TATAINVEST.NS",
    "TATATECH.NS",
    "THERMAX.NS",
    "TIINDIA.NS",
    "TIMKEN.NS",
    "TORNTPHARM.NS",
    "TORNTPOWER.NS",
    "TRENT.NS",
    "UBL.NS",
    "UNOMINDA.NS",
    "UPL.NS",
    "VOLTAS.NS",
    "YESBANK.NS",
    "ZFCVINDIA.NS",
    "ZYDUSLIFE.NS"
]

SMALL_CAP_STOCKS = [
    "AARTIDRUGS.NS",
    "AFFLE.NS",
    "AEGISCHEM.NS",
    "AMARAJABAT.NS",
    "AMBER.NS",
    "ANGELONE.NS",
    "ANANTRJ.NS",
    "APTUS.NS",
    "ASTERDM.NS",
    "ATUL.NS",
    "BEML.NS",
    "BLS.NS",
    "BRIGADE.NS",
    "CARYSIL.NS",
    "CCL.NS",
    "CDSL.NS",
    "CESC.NS",
    "CHAMBLFERT.NS",
    "CHOLAHLDNG.NS",
    "CIEINDIA.NS",
    "CAMS.NS",
    "CREDITACC.NS",
    "CROMPTON.NS",
    "CYIENT.NS",
    "DATAPATTNS.NS",
    "DELHIVERY.NS",
    "DEVYANI.NS",
    "EQUITASBNK.NS",
    "FINCABLES.NS",
    "FINOLEX.NS",
    "FIVESTAR.NS",
    "FIRSTSOURCE.NS",

    "GESHIP.NS",
    "GMDCLTD.NS",
    "GRANULES.NS",
    "GRSE.NS",
    "HFCL.NS",
    "HINDCOPPER.NS",
    "IBULHSGFIN.NS",
    "IDFC.NS",
    "IEX.NS",
    "IIFL.NS",
    "INDIACEM.NS",
    "INOXWIND.NS",
    "IRCON.NS",
    "ITI.NS",
    "JBCHEPHARM.NS",
    "JBMA.NS",
    "JINDALSAW.NS",
    "JKPAPER.NS",
    "JPPOWER.NS",
    "JUSTDIAL.NS",
    "JYOTHYLAB.NS",
    "KAJARIACER.NS",
    "KARURVYSYA.NS",
    "KEC.NS",
    "KIMS.NS",
    "KIRLOSENG.NS",
    "KOCHINSHIP.NS",
    "LALPATHLAB.NS",
    "LAURUSLABS.NS",

    "MANAPPURAM.NS",
    "MMTC.NS",
    "MOIL.NS",
    "NBCC.NS",
    "NCC.NS",
    "NATIONALUM.NS",
    "NAVINFLUOR.NS",
    "NEWGEN.NS",
    "NFL.NS",
    "NLCINDIA.NS",
    "NSLNISP.NS",
    "PRISMJOHN.NS",
    "PVRINOX.NS",
    "RADICO.NS",
    "RAILTEL.NS",
    "RCF.NS",
    "REDINGTON.NS",
    "RENUKA.NS",
    "RITES.NS",
    "RRKABEL.NS",
    "SOUTHBANK.NS",
    "SPICEJET.NS",
    "SUZLON.NS",
    "SWANENERGY.NS",
    "TANLA.NS",
    "TATACOFFEE.NS",
    "TATAINVEST.NS",
    "TEJASNET.NS",
    "TRIDENT.NS",
    "TRITURBINE.NS",
    "TTML.NS",
    "UCOBANK.NS",
    "UJJIVANSFB.NS",
    "UNICHEMLAB.NS",
    "WELCORP.NS",
    "WELSPUNLIV.NS",
    "ZENSARTECH.NS",
    "ZEEL.NS"
]

"""#Logic"""

# --- Install dependencies ---
#pip install yfinance ta numpy pandas matplotlib scipy -q

# --- Imports ---
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import argrelextrema
import matplotlib.pyplot as plt
import ta

def detect_rsi_divergence(df, order=5):
    df = df.copy()

    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    close = df["Close"]
    if isinstance(close, pd.DataFrame):
        close = close.squeeze()
    elif isinstance(close, pd.Series) and close.ndim > 1:
        close = close.squeeze()

    df["Close"] = close
    df["RSI"] = ta.momentum.RSIIndicator(close, window=14).rsi()
    df.dropna(inplace=True)

    min_idxs = argrelextrema(df["Close"].values, np.less_equal, order=order)[0]
    max_idxs = argrelextrema(df["Close"].values, np.greater_equal, order=order)[0]

    bullish_divs = []
    bearish_divs = []

    min_idxs_sorted = np.sort(min_idxs)
    for k in range(1, len(min_idxs_sorted)):
        i_prev = min_idxs_sorted[k-1]
        i_curr = min_idxs_sorted[k]
        if (df["Close"].iloc[i_curr] < df["Close"].iloc[i_prev]) and (df["RSI"].iloc[i_curr] > df["RSI"].iloc[i_prev]):
            bullish_divs.append(i_curr)

    max_idxs_sorted = np.sort(max_idxs)
    for k in range(1, len(max_idxs_sorted)):
        i_prev = max_idxs_sorted[k-1]
        i_curr = max_idxs_sorted[k]
        if (df["Close"].iloc[i_curr] > df["Close"].iloc[i_prev]) and (df["RSI"].iloc[i_curr] < df["RSI"].iloc[i_prev]):
            bearish_divs.append(i_curr)

    last_50_start = len(df) - 50

    bullish_recent = [idx for idx in bullish_divs if idx >= last_50_start]
    bearish_recent = [idx for idx in bearish_divs if idx >= last_50_start]

    if not bullish_recent and not bearish_recent:
        return None

    latest_bullish = max(bullish_recent) if bullish_recent else -1
    latest_bearish = max(bearish_recent) if bearish_recent else -1

    if latest_bullish > latest_bearish:
        return "bullish"
    else:
        return "bearish"

def scan_divergences(STOCKS, period="1y", interval="1d", order=5):
    results = []

    for symbol in STOCKS:
        try:
            # print(f"Processing {symbol}...")
            df = yf.download(symbol, period=period, interval=interval, auto_adjust=True, progress=False)
            # print(f"  Downloaded {len(df)} rows")
            df.dropna(inplace=True)
            # print(f"  After dropna: {len(df)} rows")

            if df.empty:
                # print(f"  Error: DataFrame is empty")
                results.append({"Stock": symbol, "Signal": "error"})
                continue

            if len(df) < 50:
                # print(f"  Error: Not enough data (need 50, got {len(df)})")
                results.append({"Stock": symbol, "Signal": "error"})
                continue

            signal = detect_rsi_divergence(df, order)
            # print(f"  Signal: {signal if signal else 'neutral'}")
            results.append({"Stock": symbol, "Signal": signal if signal else "neutral"})
        except Exception as e:
            print(f"  Error: {type(e).__name__}: {str(e)}")
            import traceback
            traceback.print_exc()
            results.append({"Stock": symbol, "Signal": "error"})

    result_df = pd.DataFrame(results)
    return result_df

def analyze_and_visualize(divergence_df, period="1y", interval="1d", order=5, save_csv=True,name="stock"):


    signal_counts = divergence_df['Signal'].value_counts()

    colors = []
    labels = []
    sizes = []

    for signal, count in signal_counts.items():
        if signal == 'bullish':
            colors.append('green')
            labels.append(f'Bullish ({count})')
            sizes.append(count)
        elif signal == 'bearish':
            colors.append('red')
            labels.append(f'Bearish ({count})')
            sizes.append(count)
        elif signal == 'neutral':
            colors.append('gray')
            labels.append(f'Neutral ({count})')
            sizes.append(count)
        elif signal == 'error':
            colors.append('orange')
            labels.append(f'Error ({count})')
            sizes.append(count)

    plt.figure(figsize=(10, 8))
    plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90, textprops={'fontsize': 12})
    plt.title('RSI Divergence Signals Distribution '+ name, fontsize=16, fontweight='bold')
    plt.axis('equal')
    plt.tight_layout()
    plt.show()

    print("\n" + "="*50)
    print("Signal Distribution:")
    print(divergence_df['Signal'].value_counts())
    print(f"\nTotal Stocks Analyzed: {len(divergence_df)}")
    print("="*50)

    if save_csv:
        divergence_df.to_csv("divergence_signals.csv", index=False)
        print("\nSaved to divergence_signals.csv")

    return divergence_df

"""#Driver

When run as a script this will perform the default scan. When imported
as a module (for example by the Flask app) the functions can be used
directly without executing the driver code."""

def run_default():
    divergence_df = scan_divergences(LARGE_CAP_STOCKS, period="1y", interval="1d", order=5)
    result = analyze_and_visualize(divergence_df, name="LARGE_CAP_STOCKS")
    return result


if __name__ == "__main__":
    run_default()